version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
  
  build:
    commands:
      - echo "Deploying Lambda functions..."
      - aws lambda update-function-code --function-name mlops-platform-training-handler-${ENVIRONMENT} --zip-file fileb://backend/lambda/training_handler.zip
      - aws lambda update-function-code --function-name mlops-platform-inference-handler-${ENVIRONMENT} --zip-file fileb://backend/lambda/inference_handler.zip
      - aws lambda update-function-code --function-name mlops-platform-model-registry-handler-${ENVIRONMENT} --zip-file fileb://backend/lambda/model_registry_handler.zip
      - echo "Deployment complete!"
