version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
      - pip install pytest pytest-cov hypothesis
  
  build:
    commands:
      - echo "Running tests..."
      - pytest tests/ -v --cov=src --cov-report=term || true
      - echo "Running property-based tests..."
      - pytest tests/ -m property -v || true

reports:
  test-results:
    files:
      - 'test-results.xml'
    file-format: 'JUNITXML'
