AWSTemplateFormatVersion: '2010-09-09'
Description: 'Data Pipeline for MLOps Platform - Glue + Step Functions'

Parameters:
  Environment:
    Type: String
    Default: dev
    Description: Environment name
  
  DataBucket:
    Type: String
    Description: S3 bucket for data storage

Resources:
  # IAM Role for Glue
  GlueExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'mlops-glue-role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole'
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:PutObject'
                  - 's3:ListBucket'
                Resource:
                  - !Sub 'arn:aws:s3:::${DataBucket}'
                  - !Sub 'arn:aws:s3:::${DataBucket}/*'

  # Glue Job for Data Validation
  DataValidationJob:
    Type: AWS::Glue::Job
    Properties:
      Name: !Sub 'mlops-data-validation-${Environment}'
      Role: !GetAtt GlueExecutionRole.Arn
      Command:
        Name: pythonshell
        PythonVersion: '3.9'
        ScriptLocation: !Sub 's3://${DataBucket}/glue-scripts/data_validation.py'
      DefaultArguments:
        '--job-language': 'python'
        '--data-bucket': !Ref DataBucket
      MaxRetries: 1
      Timeout: 60

  # Glue Job for Data Preprocessing
  DataPreprocessingJob:
    Type: AWS::Glue::Job
    Properties:
      Name: !Sub 'mlops-data-preprocessing-${Environment}'
      Role: !GetAtt GlueExecutionRole.Arn
      Command:
        Name: glueetl
        PythonVersion: '3'
        ScriptLocation: !Sub 's3://${DataBucket}/glue-scripts/data_preprocessing.py'
      DefaultArguments:
        '--job-language': 'python'
        '--data-bucket': !Ref DataBucket
      MaxRetries: 1
      Timeout: 120

  # IAM Role for Step Functions
  StepFunctionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'mlops-stepfunctions-role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: GlueAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'glue:StartJobRun'
                  - 'glue:GetJobRun'
                  - 'glue:BatchStopJobRun'
                Resource: '*'

  # Step Functions State Machine
  DataPipelineStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: !Sub 'mlops-data-pipeline-${Environment}'
      RoleArn: !GetAtt StepFunctionsRole.Arn
      DefinitionString: !Sub |
        {
          "Comment": "MLOps Data Pipeline",
          "StartAt": "DataValidation",
          "States": {
            "DataValidation": {
              "Type": "Task",
              "Resource": "arn:aws:states:::glue:startJobRun.sync",
              "Parameters": {
                "JobName": "${DataValidationJob}"
              },
              "Next": "DataPreprocessing",
              "Catch": [{
                "ErrorEquals": ["States.TaskFailed"],
                "Next": "ValidationFailed"
              }]
            },
            "DataPreprocessing": {
              "Type": "Task",
              "Resource": "arn:aws:states:::glue:startJobRun.sync",
              "Parameters": {
                "JobName": "${DataPreprocessingJob}"
              },
              "Next": "PipelineComplete",
              "Catch": [{
                "ErrorEquals": ["States.TaskFailed"],
                "Next": "PreprocessingFailed"
              }]
            },
            "PipelineComplete": {
              "Type": "Succeed"
            },
            "ValidationFailed": {
              "Type": "Fail",
              "Cause": "Data validation failed"
            },
            "PreprocessingFailed": {
              "Type": "Fail",
              "Cause": "Data preprocessing failed"
            }
          }
        }

  # EventBridge Rule for automated triggers
  DataPipelineTrigger:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub 'mlops-data-pipeline-trigger-${Environment}'
      Description: 'Trigger data pipeline on S3 uploads'
      EventPattern:
        source: ['aws.s3']
        detail-type: ['Object Created']
        detail:
          bucket:
            name: [!Ref DataBucket]
          object:
            key:
              - prefix: 'datasets/'
      State: ENABLED
      Targets:
        - Arn: !GetAtt DataPipelineStateMachine.Arn
          Id: 'DataPipelineTarget'
          RoleArn: !GetAtt StepFunctionsRole.Arn

Outputs:
  DataPipelineStateMachineArn:
    Description: Data Pipeline State Machine ARN
    Value: !Ref DataPipelineStateMachine
    Export:
      Name: !Sub 'mlops-data-pipeline-arn-${Environment}'

  DataValidationJobName:
    Description: Glue Data Validation Job Name
    Value: !Ref DataValidationJob

  DataPreprocessingJobName:
    Description: Glue Data Preprocessing Job Name
    Value: !Ref DataPreprocessingJob